branch: 'master'
repo: 'https://github.com/Mylearnings-git/mylearnings.git'
dockerrepo: 'restapi'
dockeruser: 'yuvarajkumar'
dockerimg: 'myrestapiapp'
kubcluster: 'restapi1'
kubloc: 'us-west-2'
dockercred: 'Docker'
kubcred: 'e261da0d-0895-4f7d-953f-28dbf1f27f1c'
#hello
