Gitdetails:
   branch: 'master'
   repo: 'https://github.com/Mylearnings-git/mylearnings.git'
Dockerdetails:
   dockerrepo: 'restapi'
   dockeruser: 'yuvarajkumar'
   dockerimg: 'myrestapiapp'
Kubdetails:
   kubcluster: 'restapi1'
   kubloc: 'us-west-2'
CredId:
   dockercred: 'Docker'
   kubcred: 'AWS'
Toolname:
   tool: 'Mysonarscanner'
   envname: 'Mysonar'
   file: 'sonar-project.properties'
Coverage:
  class: 'JacocoPublisher' 
  execPattern: '**/jacoco.exec'
  classPattern: '**/classes'
  sourcePattern: 'src/main/java'
  exclusionPattern: 'src/test*'
   

      
