apiVersion: apps/v1
kind: Deployment
metadata:
   name: my-deployment
   labels:
     app: myapp     
spec:
   template:
      metadata:
         name: my-rest-api
         labels:
            app: myapp
            type: front-end
      spec:
        containers:
           - name: rest-api
             image: yuvarajkumar/restapi:myapi-Build_Number
             ports:
             - containerPort: 8090
   replicas: 3
   selector:
      matchLabels:
         type: front-end
