apiVersion: apps/v1
kind: Deployment
metadata:
   name: my-deployment
   labels:
     app: myapp
spec:
   template:
      metadata:
         name: my-nginx-pod
         labels:
            app: myapp
            type: front-end
      spec:
        containers:
           - name: nginx-container
             image: nginx
   replicas: 3
   selector:
      matchLabels:
         type: front-end	
