apiVersion: v1
kind: ReplicationController
metadata:
   name: my-rc
   labels:
     app: myapp
spec:
   template:
      metadata:
         name: my-nginx-pod
         labels:
            app: myapp
            type: front-end
      spec:
        containers:
           - name: nginx-container
             image: nginx
   replicas: 3	
