apiVersion: v1
kind: Service
metadata:
   name: my-service
   labels:
     app: myapp
spec:
   type: LoadBalancer
   ports:
      - targetPort: 8090
        port: 90
   ports:
      - targetPort: 8091
        port: 91
   selector:
       app: myapp
